name: Google Cloud DNS
description: Google Cloud DNS updating service with Let's Encrypt support
version: "1.0.3"
slug: google_cloud_dns
url: https://github.com/mrmichaelrb/hassio-addons
startup: services
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - ssl:rw
  - config:ro
options:
  lets_encrypt:
    accept_terms: false
    certfile: fullchain.pem
    keyfile: privkey.pem
    renewal_period: 5184000
    dns_delay: 60
  project: project-id
  zone: zone-my-domain
  email: accountname@project-id.iam.gserviceaccount.com
  keyfile: gcp-account.p12
  keyfile_password: notasecret
  domain: my-googledns-domain.com
  ttl: 600
  scan_interval: 300
schema:
  lets_encrypt:
    accept_terms: bool
    certfile: str
    keyfile: str
    renewal_period: int
    dns_delay: int
  ipv4: str?
  ipv6: str?
  project: str
  zone: str
  email: email
  keyfile: str
  keyfile_password: str
  domain: str
  hostname: str?
  ttl: int
  scan_interval: int
